import "./globals.css";
import "@lwo/ui/styles.css";
import type { Metadata } from "next";
import { nunito } from "@lwo/ui/fonts";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
